### ISSUE TITLE
Placeholder API request

### ISSUE THREAD

**Issue by pajamaben** [spigot-gillesm/RPProfessions#1]
Hello! im super excited to begin using your plugin, and I was hoping there would be PAPI support in the future, figured I'd make a request here! Nice work so far!

**Comment by spigot-gillesm** [comment]
Hi! 

Thank you! I can add a PAPI support, what kind of placeholders would you like to use (from RPPRofessions)?

**Comment by pajamaben** [comment]
The ones I'd like the most would be %profession% and %profession_level%, but an experience one would be cool, like %profession_experience% to see how much you have and %profession_exp_to_level% to show how much you need on a scoreboard as a fraction like 20/400, though a level percentage would probably work just as well! Thanks for responding!

**Comment by spigot-gillesm** [comment]
I've added 3 new placeholders, including the ones you asked for. Check the new update entry [here](https://www.spigotmc.org/resources/rpprofessions-1-17-1-20-1-now-with-mmo-buffs.108284/update?update=520487).

I hope the update does what you were expecting.

If there's any error or you'd like other placeholders, feel free to re open this issue or open a new one.
