### ISSUE TITLE
Itemsadder support

### ISSUE THREAD

**Issue by freezyXD** [spigot-gillesm/RPProfessions#12]
I really want to use this plugin on my server, but I'm using ItemsAdder for creating custom items.

**Comment by spigot-gillesm** [comment]
Hello!

I've already worked with ItemsAdder in the past so I should be able to add this dependency without much trouble.

**Comment by spigot-gillesm** [comment]
I updated the plugin to support itemsAdder (v1.5.0). As this is a new feature, please report any bug you find by opening a new ticket like you did.
