### ISSUE TITLE
Feature Request/Issue

### ISSUE THREAD

**Issue by pajamaben** [spigot-gillesm/RPProfessions#2]
Would love a button in the different crafting menus to look at your available recipes without having to exit and run the command! Another cool thing for the dynamic crafting would be the ability to increase difficulty, like on the anvil make it have stages, or increase the amount of correct clicks it takes to successfully craft, like being able to set that per item would be awesome.  Im also having an issue with the level placeholder for the plugin, though I could make a separate issue if I need to. It returns 0 even after the player gains profession levels

**Comment by spigot-gillesm** [comment]
Hello,

I'm not sure I understand what you mean regarding the crafting menu. Right now, there's a "previous menu" button that lets you navigate between the different recipes without having to exit and re-run the /recipes command. Can you give me some details/an example of what you'd like added to the menu(s)?

I have implemented a few ways to increase the dynamic recipes difficulty, but I have to effectively include it in the final plugin. I haven't done it yet as I wanted to make sure the basics were working fine.
From what I remember:
For the Anvil: How many "right spots" must be hit, how much of your progression is lost when clicking a "wrong spot".
The Forge: At which temperature the player must remain, how close from that temperature you must remain to not "loose".
The Enchanting Table: How fast you must eliminate all the selected colours, how many rounds the player must complete.

Regarding the placeholder, can you walk me through the bug? What exactly happens before the player can notice the issue? How is the placeholder used/How is the data displayed? Is it after gaining a profession? When crafting an item that is supposed to level its profession up? Don't hesitate to include screenshots.

Thanks for the info and the suggestions!

**Comment by pajamaben** [comment]
Hey I'll write a quick update while I'm at work, In regards to the recipes I meant inside the crafting menus themselves, I think having the recipes available in the forge or anvil gui would help make everything a bit quicker for crafting, if you can't remember exactly how to craft a particular item you just would click the button and check it quick inside the forge instead of exiting the forge, running /recipes, then reopening the forge to craft the item. 
Love the ideas for specifying difficultly and I think waiting to make sure the basics work is the right move, I got excited and shouldve thought of that to be honest lol
And I'm using it specifically on my scoreboard, I can get screenshots when I get home but even when I try and get the level using PAPI it still returns a 0, the class will level correctly and show that in the chat but it won't update on the scoreboard, but when you select or remove a class that works correctly on the scoreboard.
Appreciate the plugin!

**Comment by pajamaben** [comment]
![2023-10-29_23 47 03](https://github.com/spigot-gillesm/RPProfessions/assets/10007990/d973b993-e5e4-442d-a4a9-fc932bf66e5a)
![2023-10-29_23 46 41](https://github.com/spigot-gillesm/RPProfessions/assets/10007990/ff2ba7c7-0bca-4ab3-921a-eab20500f44b)

**Comment by spigot-gillesm** [comment]
I posted an update that should fix the issue. Please download the latest (1.4.2) version of RPProfessions and the issue regarding PAPI should be resolved.

If there's still issues regarding PAPI, don't hesitate to post a message on this issue. I'll let this issue open until I've added the requested feature!

Happy building!

**Comment by spigot-gillesm** [comment]
I'm closing this issue as RPProfessions v1.4.5 implements the requested feature. Feel free to open a new issue should you need/want to.
